### ISSUE TITLE
Two issues - We discussed this paper: 1. Many mutations are from baseline; 2. There are 2 patients - but this is not shown. 

### ISSUE THREAD

**Issue by rshaferw** [hivdb/covid-drdb-payload#124] opened 2022-02-06 23:46 UTC
- [x] Many mutations are from baseline
- [x] There are 2 patients - but this is not shown for Bronstein

**Comment by KaimingTao** [comment] 2022-02-07 04:55
@rshaferw. Sorry, which paper do you refer to? Could you please share the DOI or reference nickname or author names?

**Comment by philiptzou** [comment] 2022-02-07 06:38
The baseline issue is a duplicate of hivdb/covid-drdb#25.

**Comment by philiptzou** [comment] 2022-02-07 06:44
The "patient not shown" issue is a duplicate of hivdb/chiro-frontend#55 3rd checkbox (one row per a person and a time point). Both patients are actually showed but the currently table doesn't have a way to distinguish them.

**Closed** 2022-02-07 06:49 UTC
Labels: bug
